const exportData = [
  {
    id: 3391,
    order_date: "2023-06-15",
    exporter_name: "BPS OVERSEAS PRIVATE LIMITED",
    consignee_name: "S OLIVER BERND FREIER GMBH CO KG",
    hs_code: "42022110",
    product_description: "LADIES 100% LEATHER HAND BAG OVIS GMEL",
    unit_quantity: "NOS",
    ports: "TUGLAKABAD ICD",
    foreign_port: "Rotterdam",
    foreign_country: "Germany",
    quantity: 6352,
    unit_inr_amount: 4259.85,
    total_inr_amount: 22891200,
  },
  {
    id: 3559,
    order_date: "2023-06-20",
    exporter_name: "K H EXPORTS INDIA PRIVATE LIMITED",
    consignee_name: "S OLIVER BERND FREIER GMBH AND CO",
    hs_code: "42022190",
    product_description: "SHEEP LEATHER HANDBAG",
    unit_quantity: "PCS",
    ports: "CHENNAI SEA",
    foreign_port: "Hamburg",
    foreign_country: "Germany",
    quantity: 2936,
    unit_inr_amount: 3930,
    total_inr_amount: 11387500,
  },
  {
    id: 2192,
    order_date: "2023-07-11",
    exporter_name: "SAVI LEATHERS",
    consignee_name: "AUNTS UNCLES RICHARDSTR",
    hs_code: "42022220",
    product_description: "90% CANVAS 10% LEATHER BACKPACK BAG",
    unit_quantity: "PCS",
    ports: "DADRI ICD",
    foreign_port: "Rotterdam",
    foreign_country: "Germany",
    quantity: 2730,
    unit_inr_amount: 2156950,
    total_inr_amount: 7103740000,
  },
  {
    id: 2610,
    order_date: "2023-07-24",
    exporter_name: "SAVI LEATHERS",
    consignee_name: "AUNTS UNCLES RICHARDSTR",
    hs_code: "42022220",
    product_description: "90% CANVAS 10% LEATHER SHOULDER BAG",
    unit_quantity: "PCS",
    ports: "DADRI ICD",
    foreign_port: "Rotterdam",
    foreign_country: "Germany",
    quantity: 2644,
    unit_inr_amount: 1258340,
    total_inr_amount: 4332450000,
  },
  {
    id: 2629,
    order_date: "2023-07-25",
    exporter_name: "LE CRAF",
    consignee_name: "LEDER MEID GMBH",
    hs_code: "42022190",
    product_description: "CROSSBODY BAG -90% Leather & 10% lining",
    unit_quantity: "PCS",
    ports: "JNPT/ NHAVA SHEVA SEA",
    foreign_port: "Hamburg",
    foreign_country: "Germany",
    quantity: 1884,
    unit_inr_amount: 459791,
    total_inr_amount: 1130400000,
  },
  {
    id: 2811,
    order_date: "2023-07-28",
    exporter_name: "RAHMAN LEATHER",
    consignee_name: "LEONARDO CARBONE GMBH",
    hs_code: "42022110",
    product_description: "LEATHER BAG",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Frankfurt Am Main",
    foreign_country: "Germany",
    quantity: 1872,
    unit_inr_amount: 138911,
    total_inr_amount: 299904000,
  },
  {
    id: 4361,
    order_date: "2023-05-10",
    exporter_name: "TRANSWORLD SHOES PRIVATE LIMITED",
    consignee_name: "ZIP FRIENDS GMBH CO KG",
    hs_code: "42022110",
    product_description: "LADIES LEATHER BAGS",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Frankfurt Am Main",
    foreign_country: "Germany",
    quantity: 1765,
    unit_inr_amount: 2537.06,
    total_inr_amount: 4279570,
  },
  {
    id: 1884,
    order_date: "2023-07-05",
    exporter_name: "BHOOMIKA HANDICRAFT PRIVATE LIMITED",
    consignee_name: "M S ZDZBLO GALANTERIA SKORZANA SP ZOO SP K",
    hs_code: "42022190",
    product_description: "Leather bag with shoulder strap",
    unit_quantity: "PCS",
    ports: "JODHPUR ICD",
    foreign_port: "Hamburg",
    foreign_country: "Germany",
    quantity: 1729,
    unit_inr_amount: 51451.8,
    total_inr_amount: 116225000,
  },
  {
    id: 3725,
    order_date: "2023-06-24",
    exporter_name: "SAMIK EXPORTS I PRIVATE LIMITED",
    consignee_name: "ESPRIT EUROPE SERVICES GMBH",
    hs_code: "42022190",
    product_description: "LEATHER WOMENS BAGS",
    unit_quantity: "PCS",
    ports: "JNPT/ NHAVA SHEVA SEA",
    foreign_port: "Rotterdam",
    foreign_country: "Germany",
    quantity: 1422,
    unit_inr_amount: 2591.67,
    total_inr_amount: 3514500,
  },
  {
    id: 4802,
    order_date: "2023-05-23",
    exporter_name: "SAVI LEATHERS",
    consignee_name: "AUNTS AND UNCLES",
    hs_code: "42022220",
    product_description: "90% CANVAS 10% LEATHER SHOULDER BAG",
    unit_quantity: "PCS",
    ports: "DADRI ICD",
    foreign_port: "Rotterdam",
    foreign_country: "Germany",
    quantity: 1402,
    unit_inr_amount: 2095.46,
    total_inr_amount: 2837250,
  },
  {
    id: 3006,
    order_date: "2023-06-05",
    exporter_name: "B N ENTERPRISES",
    consignee_name: "DREIMASTER MODEVERTRIEB GMBH",
    hs_code: "42022110",
    product_description: "LEATHER GOODS-LADIES BAGS",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Hamburg",
    foreign_country: "Germany",
    quantity: 1251,
    unit_inr_amount: 2563.64,
    total_inr_amount: 3204550,
  },
  {
    id: 3575,
    order_date: "2023-06-20",
    exporter_name: "STELLAR INDUSTRIES",
    consignee_name: "THREE RIVERS FASHION GMBH",
    hs_code: "42022290",
    product_description: "90% RAFFIA + 10% LEATHER LADIES HANDBAG",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Munich",
    foreign_country: "Germany",
    quantity: 1077,
    unit_inr_amount: 2718.08,
    total_inr_amount: 3179380,
  },
  {
    id: 2196,
    order_date: "2023-07-11",
    exporter_name: "SCORPIUS ENTERPRISES",
    consignee_name: "Handelsvertretung Thomas Hoffmann",
    hs_code: "42022190",
    product_description: "LADIES LEATHER BAGS",
    unit_quantity: "NOS",
    ports: "DELHI AIR",
    foreign_port: "Leipzig",
    foreign_country: "Germany",
    quantity: 1066,
    unit_inr_amount: 253681,
    total_inr_amount: 504263000,
  },
  {
    id: 4155,
    order_date: "2023-05-06",
    exporter_name: "FCG GLOBAL LLP",
    consignee_name: "EQUATORIAL GMBH",
    hs_code: "42022220",
    product_description: "70% CANVAS 30% LEATHER BAG",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Frankfurt Am Main",
    foreign_country: "Germany",
    quantity: 1047,
    unit_inr_amount: 3659.21,
    total_inr_amount: 4050600,
  },
  {
    id: 3391,
    order_date: "2023-06-15",
    exporter_name: "BPS OVERSEAS PRIVATE LIMITED",
    consignee_name: "S OLIVER BERND FREIER GMBH CO KG",
    hs_code: "42022110",
    product_description: "LADIES 100% LEATHER HAND BAG OVIS GMEL",
    unit_quantity: "NOS",
    ports: "TUGLAKABAD ICD",
    foreign_port: "Rotterdam",
    foreign_country: "Germany",
    quantity: 6352,
    unit_inr_amount: 4259.85,
    total_inr_amount: 22891200,
  },
  {
    id: 3559,
    order_date: "2023-06-20",
    exporter_name: "K H EXPORTS INDIA PRIVATE LIMITED",
    consignee_name: "S OLIVER BERND FREIER GMBH AND CO",
    hs_code: "42022190",
    product_description: "SHEEP LEATHER HANDBAG",
    unit_quantity: "PCS",
    ports: "CHENNAI SEA",
    foreign_port: "Hamburg",
    foreign_country: "Germany",
    quantity: 2936,
    unit_inr_amount: 3930,
    total_inr_amount: 11387500,
  },
  {
    id: 2192,
    order_date: "2023-07-11",
    exporter_name: "SAVI LEATHERS",
    consignee_name: "AUNTS UNCLES RICHARDSTR",
    hs_code: "42022220",
    product_description: "90% CANVAS 10% LEATHER BACKPACK BAG",
    unit_quantity: "PCS",
    ports: "DADRI ICD",
    foreign_port: "Rotterdam",
    foreign_country: "Germany",
    quantity: 2730,
    unit_inr_amount: 2156950,
    total_inr_amount: 7103740000,
  },
  {
    id: 2610,
    order_date: "2023-07-24",
    exporter_name: "SAVI LEATHERS",
    consignee_name: "AUNTS UNCLES RICHARDSTR",
    hs_code: "42022220",
    product_description: "90% CANVAS 10% LEATHER SHOULDER BAG",
    unit_quantity: "PCS",
    ports: "DADRI ICD",
    foreign_port: "Rotterdam",
    foreign_country: "Germany",
    quantity: 2644,
    unit_inr_amount: 1258340,
    total_inr_amount: 4332450000,
  },
  {
    id: 2629,
    order_date: "2023-07-25",
    exporter_name: "LE CRAF",
    consignee_name: "LEDER MEID GMBH",
    hs_code: "42022190",
    product_description: "CROSSBODY BAG -90% Leather & 10% lining",
    unit_quantity: "PCS",
    ports: "JNPT/ NHAVA SHEVA SEA",
    foreign_port: "Hamburg",
    foreign_country: "Germany",
    quantity: 1884,
    unit_inr_amount: 459791,
    total_inr_amount: 1130400000,
  },
  {
    id: 2811,
    order_date: "2023-07-28",
    exporter_name: "RAHMAN LEATHER",
    consignee_name: "LEONARDO CARBONE GMBH",
    hs_code: "42022110",
    product_description: "LEATHER BAG",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Frankfurt Am Main",
    foreign_country: "Germany",
    quantity: 1872,
    unit_inr_amount: 138911,
    total_inr_amount: 299904000,
  },
  {
    id: 4361,
    order_date: "2023-05-10",
    exporter_name: "TRANSWORLD SHOES PRIVATE LIMITED",
    consignee_name: "ZIP FRIENDS GMBH CO KG",
    hs_code: "42022110",
    product_description: "LADIES LEATHER BAGS",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Frankfurt Am Main",
    foreign_country: "Germany",
    quantity: 1765,
    unit_inr_amount: 2537.06,
    total_inr_amount: 4279570,
  },
  {
    id: 1884,
    order_date: "2023-07-05",
    exporter_name: "BHOOMIKA HANDICRAFT PRIVATE LIMITED",
    consignee_name: "M S ZDZBLO GALANTERIA SKORZANA SP ZOO SP K",
    hs_code: "42022190",
    product_description: "Leather bag with shoulder strap",
    unit_quantity: "PCS",
    ports: "JODHPUR ICD",
    foreign_port: "Hamburg",
    foreign_country: "Germany",
    quantity: 1729,
    unit_inr_amount: 51451.8,
    total_inr_amount: 116225000,
  },
  {
    id: 3725,
    order_date: "2023-06-24",
    exporter_name: "SAMIK EXPORTS I PRIVATE LIMITED",
    consignee_name: "ESPRIT EUROPE SERVICES GMBH",
    hs_code: "42022190",
    product_description: "LEATHER WOMENS BAGS",
    unit_quantity: "PCS",
    ports: "JNPT/ NHAVA SHEVA SEA",
    foreign_port: "Rotterdam",
    foreign_country: "Germany",
    quantity: 1422,
    unit_inr_amount: 2591.67,
    total_inr_amount: 3514500,
  },
  {
    id: 4802,
    order_date: "2023-05-23",
    exporter_name: "SAVI LEATHERS",
    consignee_name: "AUNTS AND UNCLES",
    hs_code: "42022220",
    product_description: "90% CANVAS 10% LEATHER SHOULDER BAG",
    unit_quantity: "PCS",
    ports: "DADRI ICD",
    foreign_port: "Rotterdam",
    foreign_country: "Germany",
    quantity: 1402,
    unit_inr_amount: 2095.46,
    total_inr_amount: 2837250,
  },
  {
    id: 3006,
    order_date: "2023-06-05",
    exporter_name: "B N ENTERPRISES",
    consignee_name: "DREIMASTER MODEVERTRIEB GMBH",
    hs_code: "42022110",
    product_description: "LEATHER GOODS-LADIES BAGS",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Hamburg",
    foreign_country: "Germany",
    quantity: 1251,
    unit_inr_amount: 2563.64,
    total_inr_amount: 3204550,
  },
  {
    id: 3575,
    order_date: "2023-06-20",
    exporter_name: "STELLAR INDUSTRIES",
    consignee_name: "THREE RIVERS FASHION GMBH",
    hs_code: "42022290",
    product_description: "90% RAFFIA + 10% LEATHER LADIES HANDBAG",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Munich",
    foreign_country: "Germany",
    quantity: 1077,
    unit_inr_amount: 2718.08,
    total_inr_amount: 3179380,
  },
  {
    id: 2196,
    order_date: "2023-07-11",
    exporter_name: "SCORPIUS ENTERPRISES",
    consignee_name: "Handelsvertretung Thomas Hoffmann",
    hs_code: "42022190",
    product_description: "LADIES LEATHER BAGS",
    unit_quantity: "NOS",
    ports: "DELHI AIR",
    foreign_port: "Leipzig",
    foreign_country: "Germany",
    quantity: 1066,
    unit_inr_amount: 253681,
    total_inr_amount: 504263000,
  },
  {
    id: 4155,
    order_date: "2023-05-06",
    exporter_name: "FCG GLOBAL LLP",
    consignee_name: "EQUATORIAL GMBH",
    hs_code: "42022220",
    product_description: "70% CANVAS 30% LEATHER BAG",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Frankfurt Am Main",
    foreign_country: "Germany",
    quantity: 1047,
    unit_inr_amount: 3659.21,
    total_inr_amount: 4050600,
  },
  {
    id: 23072023,
    order_date: "2023-07-14",
    exporter_name: "ENN LEATHERCHECKER LEATHER LIMITED",
    consignee_name: "DECO PRIVATE LIMITED",
    hs_code: "42022190",
    product_description: "GOAT LEATHER HANDBAGS",
    unit_quantity: "PCS",
    ports: "JNPT/ NHAVA SHEVA SEA",
    foreign_port: "Felixstowe",
    foreign_country: "United Kingdom",
    quantity: 8000,
    unit_inr_amount: 1151.64,
    total_inr_amount: 9213120,
  },
  {
    id: 20230520,
    order_date: "2023-05-20",
    exporter_name: "OM LEATHER ARTDECO PRIVATE LIMITED",
    consignee_name: "NO ORDINARY DESIGNER LABEL LIMITED",
    hs_code: "42022190",
    product_description:
      "20%MACHINE MADE&80%HAND MADE X BODY BAGSUSING100%BOVIN LEATHER&METAL FITTINGWITH LOGO AS DOCUMENT WE CLAIM RODTEP",
    unit_quantity: "PCS",
    ports: "KOLKATA SEA",
    foreign_port: "Felixstowe",
    foreign_country: "United Kingdom",
    quantity: 6137,
    unit_inr_amount: 2585.42,
    total_inr_amount: 15879400,
  },
  {
    id: 20230704,
    order_date: "2023-07-04",
    exporter_name: "PRIME BANOX",
    consignee_name: "NEXT RETAIL LIMITED",
    hs_code: "42022190",
    product_description: "LADIES LEATHER BAGLINING:100% POLYESTER",
    unit_quantity: "PCS",
    ports: "PIYALA ICD",
    foreign_port: "Felixstowe",
    foreign_country: "United Kingdom",
    quantity: 3939,
    unit_inr_amount: 6887,
    total_inr_amount: 27099000,
  },
  {
    id: 20230531,
    order_date: "2023-05-31",
    exporter_name: "OM LEATHER ARTDECO PRIVATE LIMITED",
    consignee_name: "NO ORDINARY DESIGNER LABEL LIMITED",
    hs_code: "42022190",
    product_description:
      "20%MACHINE MADE&80%HAND MADE X BODY BAGSUSING100%BOVIN LEATHER&METAL FITTINGWITH LOGO AS DOCUMENT WE CLAIM RODTEP E-SEAL",
    unit_quantity: "PCS",
    ports: "KOLKATA SEA",
    foreign_port: "Felixstowe",
    foreign_country: "United Kingdom",
    quantity: 3800,
    unit_inr_amount: 2388.89,
    total_inr_amount: 9357420,
  },
  {
    id: 20230726,
    order_date: "2023-07-26",
    exporter_name: "PUNIHANI INTERNATIONAL",
    consignee_name: "NATWEST",
    hs_code: "42022110",
    product_description: "LEATHER GOODS-LADIES LEATHER BAGS",
    unit_quantity: "PCS",
    ports: "JNPT/ NHAVA SHEVA SEA",
    foreign_port: "Southampton",
    foreign_country: "United Kingdom",
    quantity: 3306,
    unit_inr_amount: 2517.76,
    total_inr_amount: 8323730,
  },
  {
    id: 20230705,
    order_date: "2023-07-05",
    exporter_name: "STC INTERNATIONAL",
    consignee_name: "Z To Order and NA",
    hs_code: "42022110",
    product_description: "LEATHER LADIES HANDBAG :MACHINE & HAND",
    unit_quantity: "PCS",
    ports: "KOLKATA SEA",
    foreign_port: "Gateway",
    foreign_country: "United Kingdom",
    quantity: 2411,
    unit_inr_amount: 8068.77,
    total_inr_amount: 19451660,
  },
  {
    id: 20230717,
    order_date: "2023-07-17",
    exporter_name: "PUNIHANI INTERNATIONAL",
    consignee_name: "NATWEST",
    hs_code: "42022110",
    product_description: "LADIES LEATHER BAGS",
    unit_quantity: "PCS",
    ports: "JNPT/ NHAVA SHEVA SEA",
    foreign_port: "Southampton",
    foreign_country: "United Kingdom",
    quantity: 2164,
    unit_inr_amount: 8336.41,
    total_inr_amount: 18027270,
  },
  {
    id: 20230726,
    order_date: "2023-07-26",
    exporter_name: "BAZAAR KONNECTIONS",
    consignee_name: "NEXT RETAIL LIMITED",
    hs_code: "42022190",
    product_description: "100% LEATHER LADIES BAG",
    unit_quantity: "PCS",
    ports: "JNPT/ NHAVA SHEVA SEA",
    foreign_port: "Felixstowe",
    foreign_country: "United Kingdom",
    quantity: 2150,
    unit_inr_amount: 7258.71,
    total_inr_amount: 15593400,
  },
  {
    id: 20230706,
    order_date: "2023-07-06",
    exporter_name: "STC INTERNATIONAL",
    consignee_name: "Z To Order and NA",
    hs_code: "42022110",
    product_description: "LEATHER LADIES HANDBAG:MACHINE & HAND M",
    unit_quantity: "PCS",
    ports: "KOLKATA SEA",
    foreign_port: "Gateway",
    foreign_country: "United Kingdom",
    quantity: 2126,
    unit_inr_amount: 6331.07,
    total_inr_amount: 13457730,
  },
  {
    id: 20230520,
    order_date: "2023-05-20",
    exporter_name: "OM LEATHER ARTDECO PRIVATE LIMITED",
    consignee_name: "NO ORDINARY DESIGNER LABEL LIMITED",
    hs_code: "42022190",
    product_description:
      "20%MACHINE MADE&80%HAND MADE TOTE BAGS USING100%BOVIN LEATHER&METAL FITTING WITH LOGO AS DOCUMENT WE CLAIM RODTEP",
    unit_quantity: "PCS",
    ports: "KOLKATA SEA",
    foreign_port: "Felixstowe",
    foreign_country: "United Kingdom",
    quantity: 2118,
    unit_inr_amount: 4682.29,
    total_inr_amount: 9917090,
  },
  {
    id: 20230704,
    order_date: "2023-07-04",
    exporter_name: "PRIME BANOX",
    consignee_name: "NEXT RETAIL LIMITED",
    hs_code: "42022190",
    product_description: "LADIES LEATHER BAGLINING:100%POLYESTER",
    unit_quantity: "PCS",
    ports: "PIYALA ICD",
    foreign_port: "Felixstowe",
    foreign_country: "United Kingdom",
    quantity: 2100,
    unit_inr_amount: 1081.5,
    total_inr_amount: 2271150,
  },
  {
    id: 35222023,
    order_date: "2023-06-19",
    exporter_name: "KARENN INTERNATIONAL PRIVATE LIMITED",
    consignee_name: "S A S FPPM INTERNATIONAL",
    hs_code: "42022190",
    product_description: "LEATHER BAG",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Paris",
    foreign_country: "France",
    quantity: 11775,
    unit_inr_amount: 2359.64,
    total_inr_amount: 27726300,
  },
  {
    id: 20230712,
    order_date: "2023-07-12",
    exporter_name: "KARENN INTERNATIONAL PRIVATE LIMITED",
    consignee_name: "S A S FPPM INTERNATIONAL",
    hs_code: "42022190",
    product_description: "LEATHER BAG",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Paris",
    foreign_country: "France",
    quantity: 5000,
    unit_inr_amount: 3661.95,
    total_inr_amount: 18309750,
  },
  {
    id: 20230520,
    order_date: "2023-05-20",
    exporter_name: "KARENN INTERNATIONAL PRIVATE LIMITED",
    consignee_name: "S A S FPPM INTERNATIONAL",
    hs_code: "42022190",
    product_description: "LEATHER GOODS- LEATHER BAG",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Paris",
    foreign_country: "France",
    quantity: 4750,
    unit_inr_amount: 2353.93,
    total_inr_amount: 11072720,
  },
  {
    id: 20230807,
    order_date: "2023-08-07",
    exporter_name: "KARENN INTERNATIONAL PRIVATE LIMITED",
    consignee_name: "S A S FPPM INTERNATIONAL",
    hs_code: "42022190",
    product_description: "LEATHER BAG",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Paris",
    foreign_country: "France",
    quantity: 3950,
    unit_inr_amount: 2083.86,
    total_inr_amount: 7712360,
  },
  {
    id: 20230726,
    order_date: "2023-07-26",
    exporter_name: "KARENN INTERNATIONAL PRIVATE LIMITED",
    consignee_name: "S A S FPPM INTERNATIONAL",
    hs_code: "42022190",
    product_description: "LEATHER BAG",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Paris",
    foreign_country: "France",
    quantity: 3725,
    unit_inr_amount: 18095.87,
    total_inr_amount: 67486400,
  },
  {
    id: 20230530,
    order_date: "2023-05-30",
    exporter_name: "KARENN INTERNATIONAL PRIVATE LIMITED",
    consignee_name: "S A S FPPM INTERNATIONAL",
    hs_code: "42022190",
    product_description: "LEATHER BAG",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Paris",
    foreign_country: "France",
    quantity: 3700,
    unit_inr_amount: 2401.03,
    total_inr_amount: 8517000,
  },
  {
    id: 20230719,
    order_date: "2023-07-19",
    exporter_name: "KARENN INTERNATIONAL PRIVATE LIMITED",
    consignee_name: "S A S FPPM INTERNATIONAL",
    hs_code: "42022190",
    product_description: "LEATHER BAG",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Paris",
    foreign_country: "France",
    quantity: 3175,
    unit_inr_amount: 26619.11,
    total_inr_amount: 77777000,
  },
  {
    id: 20230515,
    order_date: "2023-05-15",
    exporter_name: "KARENN INTERNATIONAL PRIVATE LIMITED",
    consignee_name: "S A S FPPM INTERNATIONAL",
    hs_code: "42022190",
    product_description: "LEATHER GOODS: LEATHER BAG",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Paris",
    foreign_country: "France",
    quantity: 3150,
    unit_inr_amount: 2559.15,
    total_inr_amount: 7367550,
  },
  {
    id: 20230628,
    order_date: "2023-06-28",
    exporter_name: "KARENN INTERNATIONAL PRIVATE LIMITED",
    consignee_name: "S A S FPPM INTERNATIONAL",
    hs_code: "42022190",
    product_description: "LEATHER BAG",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Paris",
    foreign_country: "France",
    quantity: 2950,
    unit_inr_amount: 2442.27,
    total_inr_amount: 6809140,
  },
  {
    id: 20230612,
    order_date: "2023-06-12",
    exporter_name: "GLOBALLY YOURS",
    consignee_name: "SESSUN SAS",
    hs_code: "42022110",
    product_description: "100% LEATHER WOMEN BAG",
    unit_quantity: "PCS",
    ports: "TUGLAKABAD ICD",
    foreign_port: "Fossurmer",
    foreign_country: "France",
    quantity: 2822,
    unit_inr_amount: 2636.36,
    total_inr_amount: 7795090,
  },
  {
    id: 20230626,
    order_date: "2023-06-26",
    exporter_name: "KARENN INTERNATIONAL PRIVATE LIMITED",
    consignee_name: "S A S FPPM INTERNATIONAL",
    hs_code: "42022190",
    product_description: "LEATHER GOODS- LEATHER BAG",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Paris",
    foreign_country: "France",
    quantity: 2775,
    unit_inr_amount: 2717.19,
    total_inr_amount: 7707980,
  },
  {
    id: 20230621,
    order_date: "2023-06-21",
    exporter_name: "KARENN INTERNATIONAL PRIVATE LIMITED",
    consignee_name: "S A S FPPM INTERNATIONAL",
    hs_code: "42022190",
    product_description: "LEATHER BAG",
    unit_quantity: "PCS",
    ports: "DELHI AIR",
    foreign_port: "Paris",
    foreign_country: "France",
    quantity: 2700,
    unit_inr_amount: 2297.8,
    total_inr_amount: 5965090,
  },
  {
    id: 43382023,
    order_date: "2023-05-09",
    exporter_name: "TRITAN LEATHER WORKS PRIVATE LIMITED",
    consignee_name: "ECCO EUROPE SERVICE CENTER",
    hs_code: "42022110",
    product_description: "LEATHER HANDBAGS RFID SECURE",
    unit_quantity: "PCS",
    ports: "CHENNAI SEA",
    foreign_port: "Aarhus",
    foreign_country: "Poland",
    quantity: 10662,
    unit_inr_amount: 2613.89,
    total_inr_amount: 27466505,
  },
  {
    id: 20230509,
    order_date: "2023-05-09",
    exporter_name: "TRITAN LEATHER WORKS PRIVATE LIMITED",
    consignee_name: "ECCO EUROPE SERVICE CENTER",
    hs_code: "42022110",
    product_description: "LEATHER HANDBAGS RFID SECURE",
    unit_quantity: "PCS",
    ports: "Chennai Sea",
    foreign_port: "ARHUS",
    foreign_country: "Poland",
    quantity: 6222,
    unit_inr_amount: 2651.25,
    total_inr_amount: 16192602,
  },
  {
    id: 20230711,
    order_date: "2023-07-11",
    exporter_name: "I K INTERNATIONAL",
    consignee_name: "ZDZBLO GALANTERIA SKORZANA SP ZO O SP J",
    hs_code: "42022190",
    product_description:
      "LEATHER MADE UP GO ARTICLE / ODS / PRODUCT / ITEM - CROSSBODY BAG STYLE NO : BG4021",
    unit_quantity: "NOS",
    ports: "PANKI ICD",
    foreign_port: "Hamburg",
    foreign_country: "Poland",
    quantity: 5803,
    unit_inr_amount: 7858.22,
    total_inr_amount: 19577000,
  },
  {
    id: 20230711,
    order_date: "2023-07-11",
    exporter_name: "I K INTERNATIONAL",
    consignee_name: "ZDZBLO GALANTERIA SKORZANA SP ZO O SP J",
    hs_code: "42022190",
    product_description:
      "LEATHER MADE UP GO ARTICLE / ODS / PRODUCT / ITEM - CROSSBODY BAG STYLE NO : BG4026",
    unit_quantity: "NOS",
    ports: "PANKI ICD",
    foreign_port: "Hamburg",
    foreign_country: "Poland",
    quantity: 4704,
    unit_inr_amount: 2257.31,
    total_inr_amount: 9860900,
  },
  {
    id: 20230711,
    order_date: "2023-07-11",
    exporter_name: "I K INTERNATIONAL",
    consignee_name: "ZDZBLO GALANTERIA SKORZANA SP ZO O SP J",
    hs_code: "42022190",
    product_description:
      "LEATHER MADE UP GO ARTICLE / ODS / PRODUCT / ITEM - CROSSBODY BAG STYLE NO : BG4397-R1",
    unit_quantity: "NOS",
    ports: "PANKI ICD",
    foreign_port: "Hamburg",
    foreign_country: "Poland",
    quantity: 4001,
    unit_inr_amount: 7581.87,
    total_inr_amount: 32732730,
  },
  {
    id: 20230711,
    order_date: "2023-07-11",
    exporter_name: "I K INTERNATIONAL",
    consignee_name: "ZDZBLO GALANTERIA SKORZANA SP ZO O SP J",
    hs_code: "42022190",
    product_description:
      "LEATHER MADE UP GO ARTICLE / ODS / PRODUCT / ITEM - CROSSBODY BAG STYLE NO : BG4397",
    unit_quantity: "NOS",
    ports: "PANKI ICD",
    foreign_port: "Hamburg",
    foreign_country: "Poland",
    quantity: 3302,
    unit_inr_amount: 9010,
    total_inr_amount: 9573300,
  },
  {
    id: 20230620,
    order_date: "2023-06-20",
    exporter_name: "FARINNI LEATHER PRIVATE LIMITED",
    consignee_name: "HNI",
    hs_code: "42022290",
    product_description: "SHEEP LEATHER BUCKET BAG DTLS AS PER INV",
    unit_quantity: "PCS",
    ports: "KOLKATA SEA",
    foreign_port: "Gdynia",
    foreign_country: "Poland",
    quantity: 3000,
    unit_inr_amount: 2136.36,
    total_inr_amount: 6409092,
  },
  {
    id: 20230711,
    order_date: "2023-07-11",
    exporter_name: "I K INTERNATIONAL",
    consignee_name: "ZDZBLO GALANTERIA SKORZANA SP ZO O SP J",
    hs_code: "42022190",
    product_description:
      "LEATHER MADE UP GO ARTICLE / ODS / PRODUCT / ITEM - CROSSBODY BAG STYLE NO : BG4329-R4",
    unit_quantity: "NOS",
    ports: "PANKI ICD",
    foreign_port: "Hamburg",
    foreign_country: "Poland",
    quantity: 3000,
    unit_inr_amount: 2380.91,
    total_inr_amount: 7142730,
  },
  {
    id: 20230711,
    order_date: "2023-07-11",
    exporter_name: "I K INTERNATIONAL",
    consignee_name: "ZDZBLO GALANTERIA SKORZANA SP ZO O SP J",
    hs_code: "42022110",
    product_description:
      "LEATHER MADE UP GO ARTICLE / ODS / PRODUCT / ITEM - WOMEN HANDBAG STYLE NO :BG5516",
    unit_quantity: "NOS",
    ports: "PANKI ICD",
    foreign_port: "Hamburg",
    foreign_country: "Poland",
    quantity: 2003,
    unit_inr_amount: 5963.67,
    total_inr_amount: 19272730,
  },
  {
    id: 20230718,
    order_date: "2023-07-18",
    exporter_name: "SAAM IMPEX",
    consignee_name: "KONEKO JURIJ VIKKAGE SEREDYNKA",
    hs_code: "42022190",
    product_description: "MENS LEATHER BAGS B",
    unit_quantity: "PCS",
    ports: "TUGLAKABAD ICD",
    foreign_port: "Gdynia",
    foreign_country: "Poland",
    quantity: 2001,
    unit_inr_amount: 1083.33,
    total_inr_amount: 2166670,
  },
  {
    id: 9999999999,
    order_date: "2023-07-18",
    exporter_name: "SAAM IMPEX",
    consignee_name: "KONEKO JURIJ VIKKAGE SEREDYNKA",
    hs_code: "42022190",
    product_description: "MENS LEATHER BAGS B",
    unit_quantity: "PCS",
    ports: "TUGLAKABAD ICD",
    foreign_port: "Gdynia",
    foreign_country: "USA",
    quantity: 2001,
    unit_inr_amount: 1083.33,
    total_inr_amount: 2166670,
  },
];

export { exportData as default };
